### ISSUE TITLE
Chinese can't download any files from dropbox

### ISSUE THREAD

**Issue by zaoqi** [bfabiszewski/kterm#11] opened 2017-03-04 11:21 UTC

**Comment by bfabiszewski** [comment] 2017-03-06 08:30
I am closing it as a duplicate of issue #10.

**Closed by bfabiszewski** 2017-03-06 08:30 UTC

**Comment by zaoqi** [comment] 2017-03-15 12:10
So I can't download https://dl.dropbox.com/s/ahidr95vfjhx0vn/x11vnc.zip?dl=1

**Comment by bfabiszewski** [comment] 2017-03-16 07:11
Oh I see what you mean.
While it is not a kterm issue, here is your requested file: [x11vnc.zip](https://github.com/bfabiszewski/kterm/files/846918/x11vnc.zip)

**Comment by bfabiszewski** [comment] 2017-03-16 07:18
And all the remaining ones from my [website](https://www.fabiszewski.net/kindle-terminal/).
[elinks.zip](https://github.com/bfabiszewski/kterm/files/846921/elinks.zip)
[ettercap.zip](https://github.com/bfabiszewski/kterm/files/846923/ettercap.zip)
[coreutils-8.17.zip](https://github.com/bfabiszewski/kterm/files/846924/coreutils-8.17.zip)
[lftp.zip](https://github.com/bfabiszewski/kterm/files/846925/lftp.zip)
[ffmpeg.zip](https://github.com/bfabiszewski/kterm/files/846926/ffmpeg.zip)
[mcabber.zip](https://github.com/bfabiszewski/kterm/files/846927/mcabber.zip)
[mlocate.zip](https://github.com/bfabiszewski/kterm/files/846922/mlocate.zip)
[screen.zip](https://github.com/bfabiszewski/kterm/files/846928/screen.zip)
[mplayer.zip](https://github.com/bfabiszewski/kterm/files/846929/mplayer.zip)
[strace.zip](https://github.com/bfabiszewski/kterm/files/846930/strace.zip)
[tcpdump.zip](https://github.com/bfabiszewski/kterm/files/846932/tcpdump.zip)
[tmux.zip](https://github.com/bfabiszewski/kterm/files/846931/tmux.zip)
[tt.zip](https://github.com/bfabiszewski/kterm/files/846933/tt.zip)
[ulogd.zip](https://github.com/bfabiszewski/kterm/files/846934/ulogd.zip)
[vim.zip](https://github.com/bfabiszewski/kterm/files/846935/vim.zip)
[wget.zip](https://github.com/bfabiszewski/kterm/files/846936/wget.zip)
